# Connection parameters
connection:
    url: jdbc:mysql://localhost:3306/
    poolSize: 5

# Protocols
protocols:
   - http
   - https

# Users
users:
    katta: katta

# Port Info :
#     Agency server : 1997
#     Airline server : 1998
#     Hotel Server : 1999